### ISSUE TITLE
"Sorry this adobe app is not available"

### ISSUE THREAD

**Issue by antoniovalentino** [YarosMallorca/adobe_deactivation_bypass#1]
When open the app, after 10 second a pop up says "Sorry this adobe app is not available".
You are forced to close the app, so the bypass doesn't work.

**Comment by YarosMallorca** [comment]
I'll look into it!

**Comment by YarosMallorca** [comment]
@maciej-nawrocki @antoniovalentino
Please try the newest version, I have added more IPs to the blocklist:
https://github.com/YarosMallorca/adobe_deactivation_bypass/releases/tag/V1.1.0

**Comment by YarosMallorca** [comment]
Will close for now as "can't repro" because I cannot get this behavior of my part.
