### ISSUE TITLE
Photoshop Crashing

### ISSUE THREAD

**Issue by tomisin110** [YarosMallorca/adobe_deactivation_bypass#2]
I have been using this fix on my m1 MacBook Pro in pairing with Lulu firewall on Photoshop in 2022. I have used yesterday's fix but it keeps crashing—any advice on what to do?

**Comment by YarosMallorca** [comment]
Disable the firewall and try only using this fix. If that doesn't work, then it's probably Adobe adding more IPs to their checklist. I don't have time to add them all, I am trying to keep this up to date, but if that doesn't work, try find another solution...

**Comment by tomisin110** [comment]
> Disable the firewall and try only using this fix. If that doesn't work, then it's probably Adobe adding more IPs to their checklist. I don't have time to add them all, I am trying to keep this up to date, but if that doesn't work, try find another solution...

Ok. will do Thanks

**Comment by YarosMallorca** [comment]
@tomisin110 Could you please download the [latest version](https://github.com/YarosMallorca/adobe_deactivation_bypass/releases/latest) and try again, confirm if it works or not?

Thanks!
