### ISSUE TITLE
Consider using a.dove.isdumb as a blocklist source

### ISSUE THREAD

**Issue by renb0** [YarosMallorca/adobe_deactivation_bypass#3]
A comprehensive and frequently updated list of adobe IPs can be found on https://a.dove.isdumb

The repo is here: https://github.com/ignaciocastro/a-dove-is-dumb

**Comment by YarosMallorca** [comment]
Thanks for letting me know this exists!
Should I only block those specified by "a.dove.isdumb" or also the ones I have currently?

**Comment by YarosMallorca** [comment]
I have already switched to using it in another branch (https://github.com/YarosMallorca/adobe_deactivation_bypass/pull/4), and soon will be merging it into main!
