### ISSUE TITLE
"Sorry this adobe app is not available"

### ISSUE THREAD

**Issue by junhuili** [YarosMallorca/adobe_deactivation_bypass#5]
Same issue as #1 for Adobe illustrator 2024.
<img width="619" alt="Screenshot 2024-09-29 at 11 58 34 AM" src="https://github.com/user-attachments/assets/9faf9c97-35aa-4177-89da-ac32f3477087">

**Comment by YarosMallorca** [comment]
You'll have to use an older version of Illustrator.
In my experience anything 2020 and older will work.

**Comment by junhuili** [comment]
Thanks

**Comment by junhuili** [comment]
What's the recommended way to revert to the status before running the tool?
